import * as utils from './utils.js';

console.log(utils.productInfo("Sách", 20000));
console.log(utils.greet("An"));
console.log(utils.sumUpTo(5));
console.log(utils.square(6));
console.log(utils.isEven(7));
console.log(utils.firstElement([1, 2, 3]));
console.log(utils.sum(1, 2, 3, 4));
console.log(utils.formatUser({ name: "Nam", age: 30 }));
console.log(utils.listNames([{ name: "An" }, { name: "Bình" }]));
console.log(utils.stringLength("Hello World"));
console.log(utils.toUpperCase("javascript"));
console.log(utils.formatCurrency(1000000));
console.log(utils.max([10, 5, 20, 8]));
console.log(utils.isPrime(7));
console.log(utils.repeatString("Hello", 3));
console.log(utils.sumOdd([1, 2, 3, 4]));
console.log(utils.sumGreaterThan([1, 2, 3, 4], 2));
console.log(utils.formatDate("2024-11-28"));
console.log(utils.firstThree([1, 2, 3, 4, 5]));
console.log(utils.containsChar("javascript", "j"));
console.log(utils.mergeArrays([1, 2], [3, 4]));
console.log(utils.countOccurrences([1, 2, 2, 3, 2], 2));
console.log(utils.filterOdd([1, 2, 3, 4]));
console.log(utils.greaterThan([1, 2, 3, 4], 2));
console.log(utils.factorial(5));
console.log(utils.separateEvenOdd([1, 2, 3, 4]));
console.log(utils.sortAsc([3, 1, 4, 2]));
console.log(utils.sumEvenIndex([1, 2, 3, 4]));
console.log(utils.multiplyByTwo([1, 2, 3]));
console.log(utils.arrayToString(["a", "b", "c"]));