import * as utils from './utils.js';

console.log(utils.sumArray([1, 2, 3, 4]));
console.log(utils.countOccurrences([1, 2, 2, 3, 2], 2));
console.log(utils.removeDuplicates([1, 2, 2, 3, 4, 4, 6, 2, 3, 6]));
console.log(utils.flattenArray([[1, 2], [3, 4]]));
console.log(utils.isSymmetric([1, 2, 3, 2, 1]));
console.log(utils.findSecondLargest([3, 1, 4, 2, 4]));
console.log(utils.sortProductsByPrice([{ name: 'Product A', price: 30 }, { name: 'Product B', price: 20 }, { name: 'Product C', price: 50 }]));
console.log(utils.findMostExpensiveProduct([{ name: 'Product A', price: 30 }, { name: 'Product B', price: 20 }, { name: 'Product C', price: 50 }]));
console.log(utils.groupByType([{ type: 'fruit', name: 'apple' }, { type: 'vegetable', name: 'carrot' }, { type: 'fruit', name: 'banana' }]));
console.log(utils.isSubset([1, 2, 3, 4], [2, 4]));
console.log(utils.findMaxKey({ a: 10, b: 20, c: 15 }));
console.log(utils.mergeObjectsSumValues({ a: 10, b: 20 }, { b: 30, c: 40 }));
console.log(utils.countElements(['a', 'b', 'a', 'c', 'b', 'a']));
console.log(utils.cleanObject({ a: 1, b: null, c: undefined, d: 4 }));
console.log(utils.hasDuplicate([1, 2, 3, 4, 2]));
console.log(utils.sumByGroup([{ type: 'fruit', price: 10 }, { type: 'vegetable', price: 20 }, { type: 'fruit', price: 30 }]));
console.log(utils.uniqueValues([1, 2, 3], [3, 4, 5]));
console.log(utils.isPermutation([1, 2, 3], [3, 2, 1]));
console.log(utils.findLongestString(['abc', 'abcd', 'a']));
console.log(utils.intersection([1, 2, 3], [2, 3, 4]));
console.log(utils.filterByMinValue([5, 10, 15, 20], 12));
console.log(utils.findLongestValue({ a: 'cat', b: 'elephant', c: 'dog' }));
console.log(utils.groupByFirstLetter(['apple', 'banana', 'avocado', 'blueberry']));
console.log(utils.getAdults([{ name: 'Alice', age: 17 }, { name: 'Bob', age: 20 }, { name: 'Charlie', age: 16 }, { name: 'David', age: 22 }]));
console.log(utils.convertToArray({ a: 1, b: 2, c: 3 }));
console.log(utils.sortStringsByLength(['a', 'ccc', 'bb']));
console.log(utils.sumByKey([{ type: 'fruit', price: 10 }, { type: 'vegetable', price: 20 }, { type: 'fruit', price: 30 }], 'price'));
console.log(utils.countWords("Hello world! Welcome to JavaScript"));
console.log(utils.findMinKey({ a: 100, b: 20, c: 50 }));